### PR TITLE
Check `Context` has a `reflector` and is not nested

### LINKED ISSUE #1822: Version 5.5.0 adds a type when there is no type defined
Actually, it changes the type of properties without type to the return type of the method.
here the return type is float, so properties without type are now float

```php
#[\OpenApi\Attributes\Post(
        path: '/test',
        description: 'test',
        summary: 'test',
        operationId: 'test',
        tags: ['test'],
        requestBody: new \OpenApi\Attributes\RequestBody(content: [new OA\MediaType(
            mediaType: 'application/json',
            schema: new \OpenApi\Attributes\Schema(
                required: ['note'],
                properties: [
                    new \OpenApi\Attributes\Property(property: 'note', example: 'My note'),
                    new \OpenApi\Attributes\Property(
                        property: 'test2',
                        description: 'test2',
                        oneOf: [
                            new \OpenApi\Attributes\Schema(type: Blah::class),
                            new \OpenApi\Attributes\Schema(type: Blah2::class),
                        ]
                    ),
                ]
            )
        )]),
        responses: [
            new \OpenApi\Attributes\Response(
                description: 'test',
                response: 'default',
            ),

        ]
    )]
    public function test2(): float
    {
        return 1.1;
    }

#[\OpenApi\Attributes\Schema()]
class Blah
{
}
#[\OpenApi\Attributes\Schema()]
class Blah2
{
}
```

It generates
```json
"\/test": {
            "post": {
                "tags": [
                    "test"
                ],
                "summary": "test",
                "description": "test",
                "operationId": "test",
                "requestBody": {
                    "content": {
                        "application\/json": {
                            "schema": {
                                "required": [
                                    "note"
                                ],
                                "properties": {
                                    "note": {
                                        "type": "number",
                                        "format": "float",
                                        "example": "My note"
                                    },
                                    "test2": {
                                        "description": "test2",
                                        "type": "number",
                                        "format": "float",
                                        "oneOf": [
                                            {
                                                "$ref": "#\/components\/schemas\/Blah"
                                            },
                                            {
                                                "$ref": "#\/components\/schemas\/Blah2"
                                            }
                                        ]
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "default": {
                        "description": "test"
                    }
                }
            }
        },
```

### LINKED ISSUE #1823: TypeError in AugmentProperties
**Version:** (v5.5.0)
**Framework:** Symfony (via NelmioApiDocBundle integration)

### Description

After updating to the latest version, Swagger generation crashes with the following error:

```
OpenApi\Type\LegacyTypeResolver::getDocblockTypeDetails(): 
Argument #1 ($reflector) must be of type Reflector, null given, 
called in vendor/zircote/swagger-php/src/Processors/AugmentProperties.php on line 78
```

### Stack Trace
```
in vendor/zircote/swagger-php/src/Type/LegacyTypeResolver.php:101
in vendor/zircote/swagger-php/src/Processors/AugmentProperties.php:78
in vendor/zircote/swagger-php/src/Processors/AugmentProperties.php:45
in vendor/zircote/swagger-php/src/Pipeline.php:113
in vendor/nelmio/api-doc-bundle/src/Render/RenderOpenApi.php:85
```

### Additional Context

The issue appears to be triggered when `$property->getContext()` or similar returns `null`, leading to a null `$reflector` being passed to `LegacyTypeResolver::getDocblockTypeDetails()`.

Likely introduced by recent refactorings in the `AugmentProperties` processor.

### PR DESCRIPTION
**Pull request by DerManoMann**
Fixes #1823, Fixes #1822 

Not sure it fixes it in the sense that the generated spec is correct, but it should avoid the `null` error.

### CODE REVIEW

File: src/Processors/AugmentProperties.php [hunk 1]
```diff
@@ -70,6 +70,11 @@ public function __invoke(Analysis $analysis): void
     protected function augmentSchemaType(Analysis $analysis, OA\Schema $schema): void
     {
         $context = $schema->_context;
+
+        if (!$context->reflector || $context->is('nested')) {
```
Comment (garak) [inline src/Processors/AugmentProperties.php]: `!$context->reflector` should be `null === $context->reflector` instead (avoiding type juggling)
